### ISSUE TITLE
sundr-codegen shading issues

### ISSUE THREAD

**Issue by mattnelson** [sundrio/sundrio#153]
The shading of sundr-codegen introduced in #101 can cause runtime issues with duplicate classes. If a project also depends on commons-lang, there will be two versions of those classes on the classpath and the sundr version is 2.4 where as the current latest is [2.6](https://search.maven.org/search?q=g:commons-lang%20AND%20a:commons-lang&core=gav).

Possible solutions (ordered in my preference):
1. Publish two sundr-codegen artifacts, one shaded and one not.
1. Relocate all transitive dependencies (should probably also be combined with 1)
1. Always keep sundr-codegen up to date on all dependencies to minimize the chance of conflicts. It isn't a huge deal if two versions of commons-lang-2.6 are on the classpath.

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ sundr-codegen ---
[INFO] io.sundr:sundr-codegen:jar:0.19-SNAPSHOT
[INFO] +- io.sundr:sundr-core:jar:0.19-SNAPSHOT:compile
[INFO] +- com.github.javaparser:javaparser-core:jar:2.4.0:compile 		<- relocated
[INFO] +- org.apache.velocity:velocity:jar:1.7:compile 					<- relocated
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile	<- NOT relocated	
[INFO] |  \- commons-lang:commons-lang:jar:2.4:compile					<- NOT relocated	
[INFO] +- junit:junit:jar:4.12:test
[INFO] \- com.sun:tools:jar:1.7:system
```

**Comment by mattnelson** [comment]
Digging into this a little more, I now think this an issue with the kubernetes client[1] dependency scope which is causing retention past the compilation phase. Similar compilation annotation processors[2] recommend using optional scope.

This was discovered with a maven enforcer rule which detects duplicate classes[3].

[1] https://github.com/kubernetes-client/java/blob/client-java-parent-5.0.0/kubernetes/pom.xml#L131-L142
[2] https://github.com/google/auto/tree/master/service#download
[3] https://www.mojohaus.org/extra-enforcer-rules/banDuplicateClasses.html

**Comment by iocanel** [comment]
@mattnelson: while I agree, that the issue could possibly be solved with the right scope, I do find your suggestions reasonable.

So, I could work on providing to variants of sundr-codegen and having everything relocated.
I can't guarantee though that I can keep everything up to date, as most are transitives of velocity and there hasn't been a velocity release in ages.

**Comment by frrivero** [comment]
Hi, adding io.kubernetes.java-client dependency is including sundr-cogeden.commons-lang:2.4 and is overwriting my StringUtils class, which is causing some methods to disappear, I have a direct dependency on commons-lang:2.6 and still gets overwritten.
kube-client:10.0.0

**Comment by eolivelli** [comment]
This is my fix, that is to keep the codegen in scope "provided", this way it does not affect final distribution libraries.
 

```
<dependency>
    <groupId>io.kubernetes</groupId>
    <artifactId>client-java</artifactId>
    <version>${kubernetesclient.version}</version>
    <scope>compile</scope>
    <exclusions>
      <exclusion>
            <groupId>io.sundr</groupId>
            <artifactId>*</artifactId>
      </exclusion>
      <exclusion>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
      </exclusion>
    </exclusions>
  </dependency>
  <dependency>
    <groupId>io.sundr</groupId>
    <artifactId>sundr-codegen</artifactId>
    <version>${sundr.version}</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>io.sundr</groupId>
    <artifactId>sundr-core</artifactId>
    <version>${sundr.version}</version>
    <scope>provided</scope>
  </dependency>
```

**Comment by iocanel** [comment]
We are moving towards eliminated shading of dependencies all together by eliminating `velocity` and `github-java-parser` dependencies. The plan is that `builder-anntoations` will be 100% of non-sundrio dependencies.

**Comment by iocanel** [comment]
At the moment the only sundrio artifacts that use external dependencies are:
- sundr-adapter-source (depends on github-java-parser).
- sundr-codegen-velocity (depends on apache velocity).

Also, these are no longer used by `builder-annotations` so, I expect kubernetes-client users to have no more issues with that.
I'll look into providing dual versions for those artifacts (shaded / unshaded).

**Comment by iocanel** [comment]
The following changes have been added to the current master and are planned for a 0.50.0 release:

- `builder-annotations` no longer depends in any way from external dependencies (no velocity dependency, no github-java-parsers).
- `transforma-annotations` no longer has external dependenices however it will need either `sundr-codegen-velocotiy` or `sundr-codegen-st4` to work. Both modules are also available with the `-nodeps` suffix which implies no dependency shaded uberjar.

I think we can close this now
